### ISSUE TITLE
devel doesn't work

### ISSUE THREAD

**Issue by SlightlySwissGuy** [ZGoriely/Weather#10]
Running devel, I get the following stacktrace:

4 8
Exception in thread "main" Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at uk.ac.cam.groupseven.weatherapp.SlidingLayoutManager.layoutContainer(SlidingLayoutManager.java:43)
	at java.awt.Container.layout(Container.java:1512)
	at java.awt.Container.doLayout(Container.java:1501)
	at java.awt.Container.validateTree(Container.java:1697)
	at java.awt.Container.validateTree(Container.java:1706)
	at java.awt.Container.validateTree(Container.java:1706)
	at java.awt.Container.validateTree(Container.java:1706)
	at java.awt.Container.validate(Container.java:1632)
	at java.awt.Window.dispatchEventImpl(Window.java:2744)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
java.lang.NullPointerException
	at uk.ac.cam.groupseven.weatherapp.SlidingLayoutManager.layoutContainer(SlidingLayoutManager.java:43)
	at java.awt.Container.layout(Container.java:1512)
	at java.awt.Container.doLayout(Container.java:1501)
	at java.awt.Container.validateTree(Container.java:1697)
	at java.awt.Container.validateTree(Container.java:1706)
	at java.awt.Container.validateTree(Container.java:1706)
	at java.awt.Container.validateTree(Container.java:1706)
	at java.awt.Container.validate(Container.java:1632)
	at java.awt.Container.validateUnconditionally(Container.java:1669)
	at java.awt.Window.pack(Window.java:818)
	at uk.ac.cam.groupseven.weatherapp.MainForm.main(MainForm.java:18)

Line 18 in MainForm.java is where frame.pack() is called

Is this just my setup being wrong?

**Comment by SlightlySwissGuy** [comment]
Found the issue.
IntelliJ code analysis told us we could replace a big if-else-if block with a switch statement.
However, the if-else block was cool with null values whereas switch statements don't work with null values.
The program was failing on line 43 of SlidingLayoutManager.java
The value SlidingLayoutManager.direction

**Comment by SlightlySwissGuy** [comment]
Don't really understand this part of the code, got to be honest

**Comment by 101hawn** [comment]
276ee3f63628a1aa31773b3df8c29a706e743636
