### ISSUE TITLE
Theming branch has intermittent crashing

### ISSUE THREAD

**Issue by SlightlySwissGuy** [ZGoriely/Weather#12]
This intermittently crashes (every few times it is run) with the output:
4 8

And stacktrace:

Exception in thread "main" java.lang.IllegalArgumentException: layoutState cannot be null
at com.intellij.uiDesigner.core.DimensionInfo.(DimensionInfo.java:36)
at com.intellij.uiDesigner.core.VerticalInfo.(VerticalInfo.java:20)
at com.intellij.uiDesigner.core.GridLayoutManager.validateInfos(GridLayoutManager.java:585)
at com.intellij.uiDesigner.core.GridLayoutManager.layoutContainer(GridLayoutManager.java:392)
at java.awt.Container.layout(Container.java:1512)
at java.awt.Container.doLayout(Container.java:1501)
at java.awt.Container.validateTree(Container.java:1697)
at java.awt.Container.validateTree(Container.java:1706)
at java.awt.Container.validateTree(Container.java:1706)
at java.awt.Container.validateTree(Container.java:1706)
at java.awt.Container.validateTree(Container.java:1706)
at java.awt.Container.validate(Container.java:1632)
at java.awt.Container.validateUnconditionally(Container.java:1669)
at java.awt.Window.show(Window.java:1033)
at java.awt.Component.show(Component.java:1671)
at java.awt.Component.setVisible(Component.java:1623)
at java.awt.Window.setVisible(Window.java:1014)
at uk.ac.cam.groupseven.weatherapp.MainForm.main(MainForm.java:21)

Any idea why this is happening?
(line 21 is frame.setVisible(true) )

**Comment by 101hawn** [comment]
Pretty sure this was present in develop branch as well

**Comment by 101hawn** [comment]
Fixed? @SlightlySwissGuy

**Comment by SlightlySwissGuy** [comment]
4 8
Exception in thread "main" java.lang.IllegalArgumentException: layoutState cannot be null
	at com.intellij.uiDesigner.core.DimensionInfo.<init>(DimensionInfo.java:36)
	at com.intellij.uiDesigner.core.VerticalInfo.<init>(VerticalInfo.java:20)
	at com.intellij.uiDesigner.core.GridLayoutManager.validateInfos(GridLayoutManager.java:585)
	at com.intellij.uiDesigner.core.GridLayoutManager.layoutContainer(GridLayoutManager.java:392)
	at java.awt.Container.layout(Container.java:1512)
	at java.awt.Container.doLayout(Container.java:1501)
	at java.awt.Container.validateTree(Container.java:1697)
	at java.awt.Container.validateTree(Container.java:1706)
	at java.awt.Container.validateTree(Container.java:1706)
	at java.awt.Container.validateTree(Container.java:1706)
	at java.awt.Container.validateTree(Container.java:1706)
	at java.awt.Container.validate(Container.java:1632)
	at java.awt.Container.validateUnconditionally(Container.java:1669)
	at java.awt.Window.show(Window.java:1033)
	at java.awt.Component.show(Component.java:1671)
	at java.awt.Component.setVisible(Component.java:1623)
	at java.awt.Window.setVisible(Window.java:1014)
	at uk.ac.cam.groupseven.weatherapp.MainForm.main(MainForm.java:19)

Not fixed

**Comment by SlightlySwissGuy** [comment]
I tell a lie
It now seems to work consistently. I think IntelliJ may have not updated it properly after I did a pull so I ran the old version on first test
